[general]
import = [
  # "/home/miku4j/repo/dotfiles/alacritty/catppuccin-mocha.toml"
  "/home/miku4j/repo/dotfiles/alacritty/ayu-dark.toml"
]

[window]
startup_mode = "Maximized"

[env]
TERM = "xterm-256color"

[font]
normal = { family = "FiraCode Nerd Font"}
size = 11.5
