model: gpt41mini
api-key:
  - gemini=
  - openrouter=
alias:
  - 2:gemini/gemini-2.0-flash
  - 25p:gemini/gemini-2.5-pro-preview-03-25
  - 25f:gemini/gemini-2.5-flash-preview-04-17
  - o25:openrouter/google/gemini-2.5-pro-preview-03-25
  - 3:openrouter/deepseek/deepseek-chat-v3-0324
  - r1:openrouter/deepseek/deepseek-r1
  - gpt41mini:openrouter/openai/gpt-4.1-mini
  - gpt41:openrouter/openai/gpt-4.1
dark-mode: true
auto-commits: false
watch-files: true
cache-prompts: true
