#! /usr/bin/bash

# Pull my dotfiles
chezmoi init --apply https://github.com/ahmaddynugroho/dotfiles
# Install MOST IMPORTANT PACKAGE!!!
sudo pacman -Sy --needed - < ~/.pkglist
# ofc it's neovim
mkdir -p ~/.config/nvim && git clone -- https://github.com/ahmaddynugroho/nvim.git ~/.config/nvim
git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim
# Configuring caps2esc
cat <<\EOF | sudo tee /etc/interception/udevmon.d/caps2esc.yaml
- JOB: intercept -g $DEVNODE | caps2esc | uinput -d $DEVNODE
  DEVICE:
    EVENTS:
      EV_KEY: [KEY_CAPSLOCK, KEY_ESC]
EOF
sudo systemctl enable udevmon
